"""update tables names

Revision ID: 03626cc797f8
Revises: 9c8b406740f4
Create Date: 2023-09-26 12:57:14.791571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03626cc797f8'
down_revision = '9c8b406740f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('patronymic', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('sex', sa.String(length=6), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=16), nullable=True),
    sa.Column('tg_nickname', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('patronymic', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('tg_nickname', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('bio', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='user_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_account_pkey')
    )
    op.drop_table('personal_data')
    # ### end Alembic commands ###
