"""user_account

Revision ID: 0fabcab90ea9
Revises: b2b8dc83ba0c
Create Date: 2023-09-10 12:37:16.722615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fabcab90ea9'
down_revision = 'b2b8dc83ba0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('sex', sa.String(length=6), nullable=True))
    op.add_column('user_account', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('user_account', sa.Column('bio', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'bio')
    op.drop_column('user_account', 'birthday')
    op.drop_column('user_account', 'sex')
    # ### end Alembic commands ###
