"""28.08 head

Revision ID: 2375d68ef56f
Revises: 435c9d84b1ea
Create Date: 2023-08-28 15:45:20.860319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2375d68ef56f'
down_revision = '435c9d84b1ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('link', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.add_column('offers', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.drop_constraint('offers_s3_filename_key', 'offers', type_='unique')
    op.drop_column('offers', 's3_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('s3_filename', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.create_unique_constraint('offers_s3_filename_key', 'offers', ['s3_filename'])
    op.drop_column('offers', 'deadline')
    op.drop_table('offer_files')
    # ### end Alembic commands ###
