"""user verify info

Revision ID: 503cc0d580f8
Revises: 14dba7f513d8
Create Date: 2023-09-28 11:35:12.155645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503cc0d580f8'
down_revision = '14dba7f513d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_verify_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('personal_data', 'patronymic',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_data', 'patronymic',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_table('user_verify_info')
    # ### end Alembic commands ###
