"""rm refresh_token

Revision ID: 60b9a1a59faf
Revises: da7047800e91
Create Date: 2023-08-27 15:02:41.743779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b9a1a59faf'
down_revision = 'da7047800e91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_session', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_session', sa.Column('refresh_token', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
