"""files table

Revision ID: 6c633631c35a
Revises: 2375d68ef56f
Create Date: 2023-08-28 15:51:04.263576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c633631c35a'
down_revision = '2375d68ef56f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
