"""del cost for offer

Revision ID: da7047800e91
Revises: 08d11a4d781c
Create Date: 2023-08-22 19:44:45.819459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7047800e91'
down_revision = '08d11a4d781c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('cost', sa.REAL(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
