"""Create on_delete const

Revision ID: f80dfef63d3f
Revises: 6c62b3bfe6d6
Create Date: 2023-08-15 14:48:24.482251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f80dfef63d3f'
down_revision = '6c62b3bfe6d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.add_column('offers', sa.Column('status_id', sa.UUID(), nullable=False))
    op.drop_constraint('offers_user_id_fkey', 'offers', type_='foreignkey')
    op.create_foreign_key(None, 'offers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'offers', 'offer_status', ['status_id'], ['id'])
    op.drop_constraint('user_account_id_fkey', 'user_account', type_='foreignkey')
    op.create_foreign_key(None, 'user_account', 'users', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_account', type_='foreignkey')
    op.create_foreign_key('user_account_id_fkey', 'user_account', 'users', ['id'], ['id'])
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.create_foreign_key('offers_user_id_fkey', 'offers', 'users', ['user_id'], ['id'])
    op.drop_column('offers', 'status_id')
    op.drop_table('offer_status')
    # ### end Alembic commands ###
